"""empty message

Revision ID: 5cda717204a5
Revises: 1b2c212aa921
Create Date: 2022-04-27 19:59:52.102129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cda717204a5'
down_revision = '1b2c212aa921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participants', sa.Column('surname', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('participants', 'surname')
    # ### end Alembic commands ###
